AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Type: String
    AllowedValues:
      - stg
      - dev
  SystemName:
    Type: String
    Default: web
    AllowedPattern: ^web$
  Purpose:
    Type: String
    Default: office
    AllowedPattern: ^office$
  WebStack:
    Type: String
  OfficeCidr:
    Type: String
    AllowedPattern: ^(([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/([1-2]?[0-9]|3[0-2])$

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Metadata
        Parameters:
          - Env
          - SystemName
          - Purpose
      - Label:
          default: Dependent Stacks
        Parameters:
          - WebStack

Resources:
  SgAlbIngressOffice:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::ImportValue:
          !Sub ${WebStack}-SgAlb
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: !Ref OfficeCidr